// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS_APIs.Data;

#nullable disable

namespace PMS_APIs.Migrations
{
    [DbContext(typeof(PmsDbContext))]
    partial class PmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS_APIs.Models.Allotment", b =>
                {
                    b.Property<string>("AllotmentId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("allotment_id");

                    b.Property<DateOnly?>("AllotmentDate")
                        .HasColumnType("date")
                        .HasColumnName("allotment_date");

                    b.Property<string>("AllotmentLetterNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("allotment_letter_no");

                    b.Property<string>("BallotNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ballot_no");

                    b.Property<DateOnly?>("BallotingDate")
                        .HasColumnType("date")
                        .HasColumnName("balloting_date");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("PossessionDate")
                        .HasColumnType("date")
                        .HasColumnName("possession_date");

                    b.Property<string>("PropertyId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("propertyid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("AllotmentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("allotments", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Cnic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cnic");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FatherName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("father_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mailing_address");

                    b.Property<string>("NomineeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nominee_id");

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nominee_name");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nominee_relation");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("passport_no");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("permanent_address");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PlanId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plan_id");

                    b.Property<string>("RegId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reg_id");

                    b.Property<string>("RegisteredSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registered_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubProject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_project");

                    b.HasKey("CustomerId");

                    b.HasIndex("Cnic");

                    b.HasIndex("Email");

                    b.HasIndex("PlanId");

                    b.HasIndex("RegId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.CustomerLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.HasKey("LogId");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_logs", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Ndc", b =>
                {
                    b.Property<string>("NdcId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ndc_id");

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issued_by");

                    b.Property<string>("NdcNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ndc_no");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("VerificationDate")
                        .HasColumnType("date")
                        .HasColumnName("verification_date");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verified_by");

                    b.HasKey("NdcId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ndcs", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("payment_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Branch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("branch");

                    b.Property<DateOnly?>("ChequeDate")
                        .HasColumnType("date")
                        .HasColumnName("cheque_date");

                    b.Property<string>("ChequeNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cheque_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount");

                    b.Property<int?>("InstallmentNo")
                        .HasColumnType("integer")
                        .HasColumnName("installment_no");

                    b.Property<decimal?>("LateFee")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("late_fee");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("net_amount");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReceiptNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receipt_no");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_no");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_date");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verified_by");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("ReferenceNo");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.PaymentPlan", b =>
                {
                    b.Property<string>("PlanId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("planid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("durationmonths");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequency");

                    b.Property<string>("PlanName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("planname");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("projectid");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("totalamount");

                    b.HasKey("PlanId");

                    b.ToTable("paymentplan", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.PaymentSchedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("scheduleid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duedate");

                    b.Property<int?>("InstallmentNo")
                        .HasColumnType("integer")
                        .HasColumnName("installmentno");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("text")
                        .HasColumnName("paymentdescription");

                    b.Property<string>("PlanId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("planid");

                    b.Property<bool?>("SurchargeApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("surchargeapplied");

                    b.Property<decimal?>("SurchargeRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("surchargerate");

                    b.HasKey("ScheduleId");

                    b.HasIndex("PlanId", "DueDate");

                    b.ToTable("paymentschedule", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Penalty", b =>
                {
                    b.Property<string>("PenaltyId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("penalty_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<DateOnly?>("PenaltyDate")
                        .HasColumnType("date")
                        .HasColumnName("penalty_date");

                    b.Property<string>("PenaltyType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("penalty_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("WaivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("waived_by");

                    b.Property<DateOnly?>("WaivedDate")
                        .HasColumnType("date")
                        .HasColumnName("waived_date");

                    b.HasKey("PenaltyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("penalties", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Possession", b =>
                {
                    b.Property<string>("PossessionId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("possession_id");

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Documents")
                        .HasColumnType("text")
                        .HasColumnName("documents");

                    b.Property<string>("HandoverBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handover_by");

                    b.Property<DateOnly?>("HandoverDate")
                        .HasColumnType("date")
                        .HasColumnName("handover_date");

                    b.Property<DateOnly?>("PossessionDate")
                        .HasColumnType("date")
                        .HasColumnName("possession_date");

                    b.Property<string>("PossessionLetterNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("possession_letter_no");

                    b.Property<string>("PropertyId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("propertyid");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("received_by");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("PossessionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("possessions", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Property", b =>
                {
                    b.Property<string>("PropertyId") 
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("propertyid");

                    b.Property<string>("Block")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("block");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coordinates");

                    b.Property<bool?>("Corner")
                        .HasColumnType("boolean")
                        .HasColumnName("corner");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Facing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facing");

                    b.Property<string>("Features")
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<bool?>("MainRoad")
                        .HasColumnType("boolean")
                        .HasColumnName("main_road");

                    b.Property<bool?>("ParkFacing")
                        .HasColumnType("boolean")
                        .HasColumnName("park_facing");

                    b.Property<string>("PlotNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plot_no");

                    b.Property<decimal?>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projectname");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubProject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_project");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PropertyId");

                    b.HasIndex("ProjectName", "Block", "PlotNo");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Refund", b =>
                {
                    b.Property<string>("RefundId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("refund_id");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text")
                        .HasColumnName("bank_details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("processed_by");

                    b.Property<DateOnly?>("ProcessedDate")
                        .HasColumnType("date")
                        .HasColumnName("processed_date");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_no");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("refund_amount");

                    b.Property<DateOnly?>("RefundDate")
                        .HasColumnType("date")
                        .HasColumnName("refund_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("RefundId");

                    b.HasIndex("CustomerId");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Registration", b =>
                {
                    b.Property<string>("RegId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reg_id");

                    b.Property<decimal?>("AgentCommission")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("agent_commission");

                    b.Property<string>("AgentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_name");

                    b.Property<decimal?>("BookingAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("booking_amount");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("PaymentPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_plan");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projectname");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_date");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubProject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_project");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_price");

                    b.HasKey("RegId");

                    b.ToTable("registration", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Transfer", b =>
                {
                    b.Property<string>("TransferId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transfer_id");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Documents")
                        .HasColumnType("text")
                        .HasColumnName("documents");

                    b.Property<string>("FromCustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("from_customer_id");

                    b.Property<string>("PropertyId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("propertyid");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("ToCustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("to_customer_id");

                    b.Property<DateOnly?>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<decimal?>("TransferFee")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("transfer_fee");

                    b.HasKey("TransferId");

                    b.HasIndex("FromCustomerId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ToCustomerId");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("userid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("RoleId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("roleid");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Waiver", b =>
                {
                    b.Property<string>("WaiverId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("waiver_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("WaiverDate")
                        .HasColumnType("date")
                        .HasColumnName("waiver_date");

                    b.Property<string>("WaiverType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("waiver_type");

                    b.HasKey("WaiverId");

                    b.HasIndex("CustomerId");

                    b.ToTable("waivers", (string)null);
                });

            modelBuilder.Entity("PMS_APIs.Models.Allotment", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Allotments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PMS_APIs.Models.Property", "Property")
                        .WithMany("Allotments")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PMS_APIs.Models.Customer", b =>
                {
                    b.HasOne("PMS_APIs.Models.PaymentPlan", "PaymentPlan")
                        .WithMany("Customers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PMS_APIs.Models.Registration", "Registration")
                        .WithMany("Customers")
                        .HasForeignKey("RegId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaymentPlan");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("PMS_APIs.Models.CustomerLog", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("CustomerLogs")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Ndc", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Ndcs")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Payment", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.PaymentSchedule", b =>
                {
                    b.HasOne("PMS_APIs.Models.PaymentPlan", "PaymentPlan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaymentPlan");
                });

            modelBuilder.Entity("PMS_APIs.Models.Penalty", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Penalties")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Possession", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Possessions")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PMS_APIs.Models.Property", "Property")
                        .WithMany("Possessions")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PMS_APIs.Models.Refund", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Refunds")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Transfer", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "FromCustomer")
                        .WithMany("TransfersFrom")
                        .HasForeignKey("FromCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PMS_APIs.Models.Property", "Property")
                        .WithMany("Transfers")
                        .HasForeignKey("PropertyId");

                    b.HasOne("PMS_APIs.Models.Customer", "ToCustomer")
                        .WithMany("TransfersTo")
                        .HasForeignKey("ToCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromCustomer");

                    b.Navigation("Property");

                    b.Navigation("ToCustomer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Waiver", b =>
                {
                    b.HasOne("PMS_APIs.Models.Customer", "Customer")
                        .WithMany("Waivers")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PMS_APIs.Models.Customer", b =>
                {
                    b.Navigation("Allotments");

                    b.Navigation("CustomerLogs");

                    b.Navigation("Ndcs");

                    b.Navigation("Payments");

                    b.Navigation("Penalties");

                    b.Navigation("Possessions");

                    b.Navigation("Refunds");

                    b.Navigation("TransfersFrom");

                    b.Navigation("TransfersTo");

                    b.Navigation("Waivers");
                });

            modelBuilder.Entity("PMS_APIs.Models.PaymentPlan", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("PMS_APIs.Models.Property", b =>
                {
                    b.Navigation("Allotments");

                    b.Navigation("Possessions");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("PMS_APIs.Models.Registration", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
